ext:
  - ".bak"
  - ".old"
  - ".rar"
  - ".zip"
  - ".tar.gz"
  - ".tar"
  - ".7z"
  - ".bz2"
  - ".gz"
  - ".z"
  - ".tgz"
  - ".db"
  - ".jar"
  - ".xz"
  - ".tar.z"
version:
  - "v1"
  - "v2"
  - "_v1"
  - "_v2"
  - "V1"
  - "V2"
  - "_V1"
  - "_V2"
  - "beta"
  - "_beta"
  - "Beta"
  - "_Beta"
  - "debug"
  - "_debug"
  - "Debug"
  - "_Debug"
  - "dev"
  - "_dev"
  - "Dev"
  - "_Dev"
